default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 20101992
  host: localhost
  database: highchart_development

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
